name: Comment Spec url on PR
on: [pull_request]
jobs:
  optic_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: trulyronak/gitbot@b05d9b9d7d66acdd09b44abde83ec1945c263156
        with:
            repository: trulyronak/gitbot
            branch: ${{ github.head_ref }}
            head: main
        id: generate_spec
      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.generate_spec.outputs.message }}
          check_for_duplicate_msg: false